language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_script:
  - wget https://github.com/samtools/htslib/releases/download/1.7/htslib-1.7.tar.bz2
  - tar jxvf htslib-1.7.tar.bz2 
  - cd htslib-1.7 && make && export PATH=$PATH:$PWD && cd ..
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.27.0/bedtools-2.27.0.tar.gz
  - tar zxvf bedtools-2.27.0.tar.gz
  - cd bedtools2 && make && export PATH=$PATH:$PWD/bin && cd ..
  - pip install annot_utils
  - pip install pysam

script:
  - pip install .
  - python setup.py test

